// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Player.Infrastructure.Persistence;

#nullable disable

namespace Player.Infrastructure.Migrations
{
    [DbContext(typeof(PlayerDbContext))]
    [Migration("20260930071706_AddSelectedHeroToPlayer")]
    partial class AddSelectedHeroToPlayer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Player.Domain.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("DungeonRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("dungeon_run_id");

                    b.Property<string>("DungeonSeed")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("dungeon_seed");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset?>("LastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at");

                    b.Property<Guid?>("MatchmakingGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("matchmaking_group_id");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mode");

                    b.Property<bool>("ProgressionRecorded")
                        .HasColumnType("boolean")
                        .HasColumnName("progression_recorded");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TerminationReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("termination_reason");

                    b.HasKey("Id");

                    b.HasIndex("MatchmakingGroupId")
                        .IsUnique();

                    b.ToTable("game_session", (string)null);
                });

            modelBuilder.Entity("Player.Domain.Entities.GameSessionMember", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid")
                        .HasColumnName("hero_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<string>("MemberStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("member_status");

                    b.HasKey("SessionId", "HeroId");

                    b.HasIndex("HeroId");

                    b.ToTable("game_session_member", (string)null);
                });

            modelBuilder.Entity("Player.Domain.Entities.GameSessionTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cause");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("SourceStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_status");

                    b.Property<string>("TargetStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("target_status");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("game_session_transition", (string)null);
                });

            modelBuilder.Entity("Player.Domain.Entities.Hero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Agility")
                        .HasColumnType("integer")
                        .HasColumnName("agility");

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("class_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Endurance")
                        .HasColumnType("integer")
                        .HasColumnName("endurance");

                    b.Property<int>("Intelligence")
                        .HasColumnType("integer")
                        .HasColumnName("intelligence");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("Strength")
                        .HasColumnType("integer")
                        .HasColumnName("strength");

                    b.HasKey("Id");

                    b.HasIndex("ClassCode");

                    b.HasIndex("PlayerId", "Name")
                        .IsUnique();

                    b.ToTable("hero", (string)null);
                });

            modelBuilder.Entity("Player.Domain.Entities.HeroClass", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<int>("BaseHealth")
                        .HasColumnType("integer")
                        .HasColumnName("base_health");

                    b.Property<int>("BaseMana")
                        .HasColumnType("integer")
                        .HasColumnName("base_mana");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("description");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.HasKey("Code");

                    b.ToTable("hero_class", (string)null);
                });

            modelBuilder.Entity("Player.Domain.Entities.HeroSkill", b =>
                {
                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid")
                        .HasColumnName("hero_id");

                    b.Property<string>("SkillCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("skill_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("UnlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at");

                    b.HasKey("HeroId", "SkillCode");

                    b.HasIndex("SkillCode");

                    b.ToTable("hero_skill", (string)null);
                });

            modelBuilder.Entity("Player.Domain.Entities.IdempotencyKey", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<Guid?>("ProducedResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("produced_resource_id");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_fingerprint");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scope");

                    b.HasKey("Key");

                    b.HasIndex("PlayerId", "Scope", "Key")
                        .IsUnique();

                    b.ToTable("idempotency_key", (string)null);
                });

            modelBuilder.Entity("Player.Domain.Entities.MatchmakingGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("FormedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("formed_at");

                    b.Property<int>("MaxNewGamePlusLevel")
                        .HasColumnType("integer")
                        .HasColumnName("max_new_game_plus_level");

                    b.Property<int>("MinNewGamePlusLevel")
                        .HasColumnType("integer")
                        .HasColumnName("min_new_game_plus_level");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("matchmaking_group", null, t =>
                        {
                            t.HasCheckConstraint("ck_matchmaking_group_level_range", "min_new_game_plus_level <= max_new_game_plus_level");
                        });
                });

            modelBuilder.Entity("Player.Domain.Entities.MatchmakingQueueEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entered_at");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid")
                        .HasColumnName("hero_id");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<int>("NewGamePlusLevelAtEntry")
                        .HasColumnType("integer")
                        .HasColumnName("new_game_plus_level_at_entry");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("HeroId");

                    b.HasIndex("PlayerId");

                    b.ToTable("matchmaking_queue_entry", (string)null);
                });

            modelBuilder.Entity("Player.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("account_status");

                    b.Property<DateTimeOffset?>("AnonymizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("anonymized_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<int>("NewGamePlusLevel")
                        .HasColumnType("integer")
                        .HasColumnName("new_game_plus_level");

                    b.Property<DateTimeOffset?>("NewGamePlusUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("new_game_plus_updated_at");

                    b.Property<Guid?>("SelectedHeroId")
                        .HasColumnType("uuid")
                        .HasColumnName("selected_hero_id");

                    b.HasKey("Id");

                    b.ToTable("player", (string)null);
                });

            modelBuilder.Entity("Player.Domain.Entities.Skill", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("class_code");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer")
                        .HasColumnName("required_level");

                    b.Property<string>("TargetingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("targeting_type");

                    b.HasKey("Code");

                    b.HasIndex("ClassCode");

                    b.ToTable("skill", (string)null);
                });

            modelBuilder.Entity("Player.Domain.Entities.GameSession", b =>
                {
                    b.HasOne("Player.Domain.Entities.MatchmakingGroup", "MatchmakingGroup")
                        .WithOne("GameSession")
                        .HasForeignKey("Player.Domain.Entities.GameSession", "MatchmakingGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MatchmakingGroup");
                });

            modelBuilder.Entity("Player.Domain.Entities.GameSessionMember", b =>
                {
                    b.HasOne("Player.Domain.Entities.Hero", "Hero")
                        .WithMany("SessionMembers")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Player.Domain.Entities.GameSession", "GameSession")
                        .WithMany("Members")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("Player.Domain.Entities.GameSessionTransition", b =>
                {
                    b.HasOne("Player.Domain.Entities.GameSession", "GameSession")
                        .WithMany("Transitions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("Player.Domain.Entities.Hero", b =>
                {
                    b.HasOne("Player.Domain.Entities.HeroClass", "HeroClass")
                        .WithMany("Heroes")
                        .HasForeignKey("ClassCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Player.Domain.Entities.Player", "Player")
                        .WithMany("Heroes")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HeroClass");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Player.Domain.Entities.HeroSkill", b =>
                {
                    b.HasOne("Player.Domain.Entities.Hero", "Hero")
                        .WithMany("HeroSkills")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player.Domain.Entities.Skill", "Skill")
                        .WithMany("HeroSkills")
                        .HasForeignKey("SkillCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hero");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Player.Domain.Entities.IdempotencyKey", b =>
                {
                    b.HasOne("Player.Domain.Entities.Player", "Player")
                        .WithMany("IdempotencyKeys")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Player.Domain.Entities.MatchmakingQueueEntry", b =>
                {
                    b.HasOne("Player.Domain.Entities.MatchmakingGroup", "Group")
                        .WithMany("QueueEntries")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Player.Domain.Entities.Hero", "Hero")
                        .WithMany("QueueEntries")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Player.Domain.Entities.Player", "Player")
                        .WithMany("QueueEntries")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Hero");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Player.Domain.Entities.Skill", b =>
                {
                    b.HasOne("Player.Domain.Entities.HeroClass", "HeroClass")
                        .WithMany("Skills")
                        .HasForeignKey("ClassCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HeroClass");
                });

            modelBuilder.Entity("Player.Domain.Entities.GameSession", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Transitions");
                });

            modelBuilder.Entity("Player.Domain.Entities.Hero", b =>
                {
                    b.Navigation("HeroSkills");

                    b.Navigation("QueueEntries");

                    b.Navigation("SessionMembers");
                });

            modelBuilder.Entity("Player.Domain.Entities.HeroClass", b =>
                {
                    b.Navigation("Heroes");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Player.Domain.Entities.MatchmakingGroup", b =>
                {
                    b.Navigation("GameSession");

                    b.Navigation("QueueEntries");
                });

            modelBuilder.Entity("Player.Domain.Entities.Player", b =>
                {
                    b.Navigation("Heroes");

                    b.Navigation("IdempotencyKeys");

                    b.Navigation("QueueEntries");
                });

            modelBuilder.Entity("Player.Domain.Entities.Skill", b =>
                {
                    b.Navigation("HeroSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
